export type SeedProduct = {
  name: string;
  unit: "un" | "kg" | "g" | "L" | "ml";
  category: string;
};

export type SeedStore = {
  name: string;
  city: string;
  notes?: string;
};

/** Catálogo amplo de itens comuns em supermercados brasileiros */
export const CATALOG_PRODUCTS: SeedProduct[] = [
  // Grãos e cereais
  { name: "Arroz branco tipo 1 5kg", unit: "un", category: "Grãos" },
  { name: "Arroz branco tipo 1 1kg", unit: "un", category: "Grãos" },
  { name: "Arroz integral 1kg", unit: "un", category: "Grãos" },
  { name: "Arroz parboilizado 5kg", unit: "un", category: "Grãos" },
  { name: "Feijão carioca 1kg", unit: "un", category: "Grãos" },
  { name: "Feijão preto 1kg", unit: "un", category: "Grãos" },
  { name: "Feijão vermelho 1kg", unit: "un", category: "Grãos" },
  { name: "Lentilha 500g", unit: "un", category: "Grãos" },
  { name: "Grão-de-bico 500g", unit: "un", category: "Grãos" },
  { name: "Ervilha seca 500g", unit: "un", category: "Grãos" },
  { name: "Aveia em flocos 200g", unit: "un", category: "Grãos" },
  { name: "Aveia em flocos 500g", unit: "un", category: "Grãos" },
  { name: "Quinoa 200g", unit: "un", category: "Grãos" },
  { name: "Milho de pipoca 500g", unit: "un", category: "Grãos" },
  { name: "Farinha de trigo 1kg", unit: "un", category: "Grãos" },
  { name: "Farinha de mandioca 500g", unit: "un", category: "Grãos" },
  { name: "Farinha de rosca 500g", unit: "un", category: "Grãos" },
  { name: "Fubá 1kg", unit: "un", category: "Grãos" },
  { name: "Amido de milho 200g", unit: "un", category: "Grãos" },
  { name: "Polvilho doce 500g", unit: "un", category: "Grãos" },
  { name: "Polvilho azedo 500g", unit: "un", category: "Grãos" },
  { name: "Tapioca granulada 500g", unit: "un", category: "Grãos" },
  { name: "Cuscuz de milho 500g", unit: "un", category: "Grãos" },
  { name: "Trigo para quibe 500g", unit: "un", category: "Grãos" },

  // Massas
  { name: "Espaguete 500g", unit: "un", category: "Massas" },
  { name: "Macarrão parafuso 500g", unit: "un", category: "Massas" },
  { name: "Macarrão penne 500g", unit: "un", category: "Massas" },
  { name: "Lasanha pré-cozida 500g", unit: "un", category: "Massas" },
  { name: "Nhoque 500g", unit: "un", category: "Massas" },
  { name: "Miojo / macarrão instantâneo", unit: "un", category: "Massas" },
  { name: "Macarrão integral 500g", unit: "un", category: "Massas" },
  { name: "Capeletti 400g", unit: "un", category: "Massas" },

  // Óleos e azeites
  { name: "Óleo de soja 900ml", unit: "un", category: "Óleos" },
  { name: "Óleo de girassol 900ml", unit: "un", category: "Óleos" },
  { name: "Óleo de milho 900ml", unit: "un", category: "Óleos" },
  { name: "Azeite de oliva extra virgem 500ml", unit: "un", category: "Óleos" },
  { name: "Azeite de oliva 500ml", unit: "un", category: "Óleos" },
  { name: "Vinagre de álcool 750ml", unit: "un", category: "Óleos" },
  { name: "Vinagre de maçã 750ml", unit: "un", category: "Óleos" },
  { name: "Vinagre balsâmico 250ml", unit: "un", category: "Óleos" },

  // Mercearia / temperos
  { name: "Açúcar cristal 1kg", unit: "un", category: "Mercearia" },
  { name: "Açúcar refinado 1kg", unit: "un", category: "Mercearia" },
  { name: "Açúcar demerara 1kg", unit: "un", category: "Mercearia" },
  { name: "Açúcar mascavo 500g", unit: "un", category: "Mercearia" },
  { name: "Adoçante 100ml", unit: "un", category: "Mercearia" },
  { name: "Sal refinado 1kg", unit: "un", category: "Mercearia" },
  { name: "Sal grosso 1kg", unit: "un", category: "Mercearia" },
  { name: "Café torrado e moído 500g", unit: "un", category: "Mercearia" },
  { name: "Café torrado e moído 250g", unit: "un", category: "Mercearia" },
  { name: "Café solúvel 100g", unit: "un", category: "Mercearia" },
  { name: "Chá mate 250g", unit: "un", category: "Mercearia" },
  { name: "Chá caixa 10 sachês", unit: "un", category: "Mercearia" },
  { name: "Achocolatado em pó 400g", unit: "un", category: "Mercearia" },
  { name: "Leite em pó 400g", unit: "un", category: "Mercearia" },
  { name: "Creme de leite 200g", unit: "un", category: "Mercearia" },
  { name: "Leite condensado 395g", unit: "un", category: "Mercearia" },
  { name: "Doce de leite 400g", unit: "un", category: "Mercearia" },
  { name: "Extrato de tomate 340g", unit: "un", category: "Mercearia" },
  { name: "Molho de tomate 340g", unit: "un", category: "Mercearia" },
  { name: "Catchup 400g", unit: "un", category: "Mercearia" },
  { name: "Mostarda 200g", unit: "un", category: "Mercearia" },
  { name: "Maionese 500g", unit: "un", category: "Mercearia" },
  { name: "Molho shoyu 150ml", unit: "un", category: "Mercearia" },
  { name: "Molho inglês 150ml", unit: "un", category: "Mercearia" },
  { name: "Caldo de galinha", unit: "un", category: "Mercearia" },
  { name: "Caldo de carne", unit: "un", category: "Mercearia" },
  { name: "Tempero completo 300g", unit: "un", category: "Mercearia" },
  { name: "Orégano 10g", unit: "un", category: "Mercearia" },
  { name: "Colorau 100g", unit: "un", category: "Mercearia" },
  { name: "Pimenta-do-reino 50g", unit: "un", category: "Mercearia" },
  { name: "Canela em pó 50g", unit: "un", category: "Mercearia" },
  { name: "Fermento químico 100g", unit: "un", category: "Mercearia" },
  { name: "Fermento biológico 10g", unit: "un", category: "Mercearia" },
  { name: "Gelatina em pó 85g", unit: "un", category: "Mercearia" },
  { name: "Chocolate em pó 200g", unit: "un", category: "Mercearia" },
  { name: "Chocolate granulado 150g", unit: "un", category: "Mercearia" },
  { name: "Coco ralado 100g", unit: "un", category: "Mercearia" },
  { name: "Leite de coco 200ml", unit: "un", category: "Mercearia" },
  { name: "Azeitona verde 200g", unit: "un", category: "Mercearia" },
  { name: "Azeitona preta 200g", unit: "un", category: "Mercearia" },
  { name: "Milho verde lata 200g", unit: "un", category: "Mercearia" },
  { name: "Ervilha lata 200g", unit: "un", category: "Mercearia" },
  { name: "Seleta de legumes 200g", unit: "un", category: "Mercearia" },
  { name: "Atum em lata 170g", unit: "un", category: "Mercearia" },
  { name: "Sardinha em lata 125g", unit: "un", category: "Mercearia" },
  { name: "Palmito 300g", unit: "un", category: "Mercearia" },
  { name: "Cogumelo conserva 200g", unit: "un", category: "Mercearia" },
  { name: "Mel 300g", unit: "un", category: "Mercearia" },
  { name: "Geleia de morango 300g", unit: "un", category: "Mercearia" },
  { name: "Pasta de amendoim 500g", unit: "un", category: "Mercearia" },
  { name: "Amendoim 500g", unit: "un", category: "Mercearia" },
  { name: "Castanha de caju 200g", unit: "un", category: "Mercearia" },
  { name: "Castanha-do-pará 200g", unit: "un", category: "Mercearia" },
  { name: "Uva-passa 200g", unit: "un", category: "Mercearia" },
  { name: "Granola 1kg", unit: "un", category: "Mercearia" },
  { name: "Cereal matinal 300g", unit: "un", category: "Mercearia" },
  { name: "Biscoito cream cracker", unit: "un", category: "Mercearia" },
  { name: "Biscoito recheado", unit: "un", category: "Mercearia" },
  { name: "Biscoito maizena", unit: "un", category: "Mercearia" },
  { name: "Torrada pacote", unit: "un", category: "Mercearia" },
  { name: "Pão de forma", unit: "un", category: "Padaria" },
  { name: "Pão francês", unit: "kg", category: "Padaria" },
  { name: "Pão de hambúrguer", unit: "un", category: "Padaria" },
  { name: "Pão integral", unit: "un", category: "Padaria" },
  { name: "Bisnaguinha", unit: "un", category: "Padaria" },
  { name: "Pão de queijo congelado 1kg", unit: "un", category: "Congelados" },

  // Laticínios
  { name: "Leite integral 1L", unit: "un", category: "Laticínios" },
  { name: "Leite desnatado 1L", unit: "un", category: "Laticínios" },
  { name: "Leite semidesnatado 1L", unit: "un", category: "Laticínios" },
  { name: "Leite zero lactose 1L", unit: "un", category: "Laticínios" },
  { name: "Leite de amêndoas 1L", unit: "un", category: "Laticínios" },
  { name: "Leite de aveia 1L", unit: "un", category: "Laticínios" },
  { name: "Iogurte natural 170g", unit: "un", category: "Laticínios" },
  { name: "Iogurte de frutas 170g", unit: "un", category: "Laticínios" },
  { name: "Iogurte grego 100g", unit: "un", category: "Laticínios" },
  { name: "Queijo mussarela", unit: "kg", category: "Laticínios" },
  { name: "Queijo prato", unit: "kg", category: "Laticínios" },
  { name: "Queijo minas frescal", unit: "kg", category: "Laticínios" },
  { name: "Queijo coalho", unit: "kg", category: "Laticínios" },
  { name: "Queijo parmesão ralado 100g", unit: "un", category: "Laticínios" },
  { name: "Queijo cottage 200g", unit: "un", category: "Laticínios" },
  { name: "Requeijão 200g", unit: "un", category: "Laticínios" },
  { name: "Cream cheese 150g", unit: "un", category: "Laticínios" },
  { name: "Manteiga 200g", unit: "un", category: "Laticínios" },
  { name: "Margarina 500g", unit: "un", category: "Laticínios" },
  { name: "Nata 200g", unit: "un", category: "Laticínios" },
  { name: "Ricota", unit: "kg", category: "Laticínios" },

  // Frios e embutidos
  { name: "Presunto", unit: "kg", category: "Frios" },
  { name: "Peito de peru", unit: "kg", category: "Frios" },
  { name: "Mortadela", unit: "kg", category: "Frios" },
  { name: "Salame", unit: "kg", category: "Frios" },
  { name: "Salsicha pacote 500g", unit: "un", category: "Frios" },
  { name: "Linguiça toscana", unit: "kg", category: "Açougue" },
  { name: "Linguiça calabresa", unit: "kg", category: "Açougue" },
  { name: "Bacon", unit: "kg", category: "Açougue" },

  // Açougue
  { name: "Carne moída", unit: "kg", category: "Açougue" },
  { name: "Patinho", unit: "kg", category: "Açougue" },
  { name: "Alcatra", unit: "kg", category: "Açougue" },
  { name: "Contrafilé", unit: "kg", category: "Açougue" },
  { name: "Filé mignon", unit: "kg", category: "Açougue" },
  { name: "Acém", unit: "kg", category: "Açougue" },
  { name: "Costela bovina", unit: "kg", category: "Açougue" },
  { name: "Fraldinha", unit: "kg", category: "Açougue" },
  { name: "Maminha", unit: "kg", category: "Açougue" },
  { name: "Picanha", unit: "kg", category: "Açougue" },
  { name: "Cupim", unit: "kg", category: "Açougue" },
  { name: "Músculo", unit: "kg", category: "Açougue" },
  { name: "Peito de frango", unit: "kg", category: "Açougue" },
  { name: "Coxa e sobrecoxa de frango", unit: "kg", category: "Açougue" },
  { name: "Frango inteiro", unit: "kg", category: "Açougue" },
  { name: "Asa de frango", unit: "kg", category: "Açougue" },
  { name: "Filé de peito de frango", unit: "kg", category: "Açougue" },
  { name: "Carne suína pernil", unit: "kg", category: "Açougue" },
  { name: "Costela suína", unit: "kg", category: "Açougue" },
  { name: "Bisteca suína", unit: "kg", category: "Açougue" },
  { name: "Lombo suíno", unit: "kg", category: "Açougue" },

  // Peixaria
  { name: "Filé de tilápia", unit: "kg", category: "Peixaria" },
  { name: "Salmão", unit: "kg", category: "Peixaria" },
  { name: "Camarão", unit: "kg", category: "Peixaria" },
  { name: "Bacalhau", unit: "kg", category: "Peixaria" },
  { name: "Sardinha fresca", unit: "kg", category: "Peixaria" },
  { name: "Merluza", unit: "kg", category: "Peixaria" },

  // Hortifruti — frutas
  { name: "Banana prata", unit: "kg", category: "Hortifruti" },
  { name: "Banana nanica", unit: "kg", category: "Hortifruti" },
  { name: "Maçã", unit: "kg", category: "Hortifruti" },
  { name: "Pera", unit: "kg", category: "Hortifruti" },
  { name: "Uva", unit: "kg", category: "Hortifruti" },
  { name: "Laranja pera", unit: "kg", category: "Hortifruti" },
  { name: "Laranja lima", unit: "kg", category: "Hortifruti" },
  { name: "Mexerica / tangerina", unit: "kg", category: "Hortifruti" },
  { name: "Limão tahiti", unit: "kg", category: "Hortifruti" },
  { name: "Limão siciliano", unit: "kg", category: "Hortifruti" },
  { name: "Abacaxi", unit: "un", category: "Hortifruti" },
  { name: "Mamão formosa", unit: "kg", category: "Hortifruti" },
  { name: "Mamão papaya", unit: "kg", category: "Hortifruti" },
  { name: "Melancia", unit: "kg", category: "Hortifruti" },
  { name: "Melão", unit: "kg", category: "Hortifruti" },
  { name: "Manga", unit: "kg", category: "Hortifruti" },
  { name: "Morango", unit: "un", category: "Hortifruti" },
  { name: "Kiwi", unit: "kg", category: "Hortifruti" },
  { name: "Abacate", unit: "kg", category: "Hortifruti" },
  { name: "Goiaba", unit: "kg", category: "Hortifruti" },
  { name: "Maracujá", unit: "kg", category: "Hortifruti" },
  { name: "Coco verde", unit: "un", category: "Hortifruti" },
  { name: "Coco seco", unit: "un", category: "Hortifruti" },

  // Hortifruti — legumes e verduras
  { name: "Tomate", unit: "kg", category: "Hortifruti" },
  { name: "Cebola", unit: "kg", category: "Hortifruti" },
  { name: "Alho", unit: "kg", category: "Hortifruti" },
  { name: "Batata inglesa", unit: "kg", category: "Hortifruti" },
  { name: "Batata doce", unit: "kg", category: "Hortifruti" },
  { name: "Cenoura", unit: "kg", category: "Hortifruti" },
  { name: "Beterraba", unit: "kg", category: "Hortifruti" },
  { name: "Abóbora", unit: "kg", category: "Hortifruti" },
  { name: "Abobrinha", unit: "kg", category: "Hortifruti" },
  { name: "Chuchu", unit: "kg", category: "Hortifruti" },
  { name: "Pepino", unit: "kg", category: "Hortifruti" },
  { name: "Pimentão", unit: "kg", category: "Hortifruti" },
  { name: "Berinjela", unit: "kg", category: "Hortifruti" },
  { name: "Vagem", unit: "kg", category: "Hortifruti" },
  { name: "Quiabo", unit: "kg", category: "Hortifruti" },
  { name: "Milho verde espiga", unit: "un", category: "Hortifruti" },
  { name: "Mandioca / aipim", unit: "kg", category: "Hortifruti" },
  { name: "Inhame", unit: "kg", category: "Hortifruti" },
  { name: "Alface americana", unit: "un", category: "Hortifruti" },
  { name: "Alface crespa", unit: "un", category: "Hortifruti" },
  { name: "Rúcula", unit: "un", category: "Hortifruti" },
  { name: "Agrião", unit: "un", category: "Hortifruti" },
  { name: "Espinafre", unit: "un", category: "Hortifruti" },
  { name: "Couve", unit: "un", category: "Hortifruti" },
  { name: "Repolho", unit: "kg", category: "Hortifruti" },
  { name: "Brócolis", unit: "un", category: "Hortifruti" },
  { name: "Couve-flor", unit: "un", category: "Hortifruti" },
  { name: "Salsinha", unit: "un", category: "Hortifruti" },
  { name: "Cebolinha", unit: "un", category: "Hortifruti" },
  { name: "Coentro", unit: "un", category: "Hortifruti" },
  { name: "Manjericão", unit: "un", category: "Hortifruti" },
  { name: "Hortelã", unit: "un", category: "Hortifruti" },
  { name: "Gengibre", unit: "kg", category: "Hortifruti" },
  { name: "Cogumelo fresco", unit: "kg", category: "Hortifruti" },

  // Ovos
  { name: "Ovos brancos dúzia", unit: "un", category: "Ovos" },
  { name: "Ovos vermelhos dúzia", unit: "un", category: "Ovos" },
  { name: "Ovos caipira dúzia", unit: "un", category: "Ovos" },

  // Bebidas
  { name: "Água mineral 1,5L", unit: "un", category: "Bebidas" },
  { name: "Água com gás 1,5L", unit: "un", category: "Bebidas" },
  { name: "Refrigerante 2L", unit: "un", category: "Bebidas" },
  { name: "Refrigerante lata 350ml", unit: "un", category: "Bebidas" },
  { name: "Suco de caixa 1L", unit: "un", category: "Bebidas" },
  { name: "Suco em pó", unit: "un", category: "Bebidas" },
  { name: "Água de coco 1L", unit: "un", category: "Bebidas" },
  { name: "Cerveja lata 350ml", unit: "un", category: "Bebidas" },
  { name: "Cerveja long neck", unit: "un", category: "Bebidas" },
  { name: "Vinho tinto 750ml", unit: "un", category: "Bebidas" },
  { name: "Energético 250ml", unit: "un", category: "Bebidas" },
  { name: "Isotônico 500ml", unit: "un", category: "Bebidas" },
  { name: "Chá gelado 1,5L", unit: "un", category: "Bebidas" },

  // Congelados
  { name: "Batata palito congelada 2kg", unit: "un", category: "Congelados" },
  { name: "Hambúrguer congelado", unit: "un", category: "Congelados" },
  { name: "Pizza congelada", unit: "un", category: "Congelados" },
  { name: "Lasanha congelada", unit: "un", category: "Congelados" },
  { name: "Nuggets de frango", unit: "un", category: "Congelados" },
  { name: "Polpa de fruta 100g", unit: "un", category: "Congelados" },
  { name: "Açaí polpa", unit: "un", category: "Congelados" },
  { name: "Sorvete 2L", unit: "un", category: "Congelados" },
  { name: "Legumes congelados 300g", unit: "un", category: "Congelados" },

  // Limpeza
  { name: "Detergente 500ml", unit: "un", category: "Limpeza" },
  { name: "Sabão em pó 1,6kg", unit: "un", category: "Limpeza" },
  { name: "Sabão líquido 3L", unit: "un", category: "Limpeza" },
  { name: "Amaciante 2L", unit: "un", category: "Limpeza" },
  { name: "Água sanitária 2L", unit: "un", category: "Limpeza" },
  { name: "Desinfetante 2L", unit: "un", category: "Limpeza" },
  { name: "Multiuso 500ml", unit: "un", category: "Limpeza" },
  { name: "Esponja de limpeza", unit: "un", category: "Limpeza" },
  { name: "Palha de aço", unit: "un", category: "Limpeza" },
  { name: "Saco de lixo 50L", unit: "un", category: "Limpeza" },
  { name: "Saco de lixo 30L", unit: "un", category: "Limpeza" },
  { name: "Papel toalha", unit: "un", category: "Limpeza" },
  { name: "Guardanapo", unit: "un", category: "Limpeza" },
  { name: "Alumínio filme", unit: "un", category: "Limpeza" },
  { name: "Filme PVC", unit: "un", category: "Limpeza" },
  { name: "Pano de prato", unit: "un", category: "Limpeza" },
  { name: "Vassoura", unit: "un", category: "Limpeza" },
  { name: "Rodo", unit: "un", category: "Limpeza" },

  // Higiene
  { name: "Papel higiênico 12 rolos", unit: "un", category: "Higiene" },
  { name: "Sabonete", unit: "un", category: "Higiene" },
  { name: "Shampoo 350ml", unit: "un", category: "Higiene" },
  { name: "Condicionador 350ml", unit: "un", category: "Higiene" },
  { name: "Creme dental", unit: "un", category: "Higiene" },
  { name: "Escova de dentes", unit: "un", category: "Higiene" },
  { name: "Fio dental", unit: "un", category: "Higiene" },
  { name: "Desodorante", unit: "un", category: "Higiene" },
  { name: "Absorvente", unit: "un", category: "Higiene" },
  { name: "Lenço umedecido", unit: "un", category: "Higiene" },
  { name: "Algodão", unit: "un", category: "Higiene" },
  { name: "Álcool 70% 1L", unit: "un", category: "Higiene" },
  { name: "Álcool gel 500ml", unit: "un", category: "Higiene" },
  { name: "Sabonete líquido 500ml", unit: "un", category: "Higiene" },
  { name: "Papel higiênico folha dupla 16 rolos", unit: "un", category: "Higiene" },

  // Pet (comum em mercado)
  { name: "Ração cães 1kg", unit: "un", category: "Pet" },
  { name: "Ração gatos 1kg", unit: "un", category: "Pet" },
  { name: "Areia sanitária 4kg", unit: "un", category: "Pet" },
];

/** Principais redes e hipermercados da cidade do Rio de Janeiro */
export const RIO_STORES: SeedStore[] = [
  { name: "Guanabara", city: "Rio de Janeiro", notes: "Rede fluminense — várias lojas na cidade" },
  { name: "Mundial", city: "Rio de Janeiro", notes: "Supermercados Mundial" },
  { name: "Prezunic", city: "Rio de Janeiro", notes: "Rede do Grupo BIG / Carrefour" },
  { name: "Zona Sul", city: "Rio de Janeiro", notes: "Rede premium — Zona Sul e Barra" },
  { name: "Hortifruti Natural da Terra", city: "Rio de Janeiro", notes: "Foco em hortifruti e orgânicos" },
  { name: "Pão de Açúcar", city: "Rio de Janeiro", notes: "GPA — várias unidades no RJ" },
  { name: "Extra", city: "Rio de Janeiro", notes: "Hipermercado GPA" },
  { name: "Carrefour", city: "Rio de Janeiro", notes: "Hipermercados e mercados na cidade" },
  { name: "Atacadão", city: "Rio de Janeiro", notes: "Atacado Carrefour — preços competitivos" },
  { name: "Assaí Atacadista", city: "Rio de Janeiro", notes: "Atacarejo — várias unidades no RJ" },
  { name: "Sam's Club", city: "Rio de Janeiro", notes: "Clube de compras — Barra / região" },
  { name: "Makro", city: "Rio de Janeiro", notes: "Atacado — região metropolitana" },
  { name: "SuperPrix", city: "Rio de Janeiro", notes: "Rede carioca de bairro" },
  { name: "Now", city: "Rio de Janeiro", notes: "Rede Now Supermercados" },
  { name: "Intercontinental", city: "Rio de Janeiro", notes: "Supermercado Intercontinental" },
  { name: "Prisma", city: "Rio de Janeiro", notes: "Supermercados Prisma" },
  { name: "Verdemar", city: "Rio de Janeiro", notes: "Presente em alguns pontos do RJ / região" },
  { name: "Mercadinho São José", city: "Rio de Janeiro", notes: "Rede de bairro" },
  { name: "Supermarket", city: "Rio de Janeiro", notes: "Rede Supermarket RJ" },
  { name: "Quitanda", city: "Rio de Janeiro", notes: "Rede Quitanda — hortifruti e mercado" },
  { name: "Greengrocer", city: "Rio de Janeiro", notes: "Hortifruti / gourmet" },
  { name: "Empório Jardim", city: "Rio de Janeiro", notes: "Empório / gourmet Zona Sul" },
  { name: "OBA Hortifruti", city: "Rio de Janeiro", notes: "Hortifruti OBA" },
  { name: "Atacado Mix", city: "Rio de Janeiro", notes: "Atacarejo região RJ" },
  { name: "Savegnago", city: "Rio de Janeiro", notes: "Quando disponível na região metropolitana" },
  { name: "Dia%", city: "Rio de Janeiro", notes: "Proximidade / lojas de bairro" },
  { name: "Minuto Pão de Açúcar", city: "Rio de Janeiro", notes: "Formato de proximidade GPA" },
  { name: "Carrefour Express", city: "Rio de Janeiro", notes: "Formato de proximidade Carrefour" },
  { name: "Mercado Livre / Full", city: "Rio de Janeiro", notes: "Compras online (referência de preço)" },
  { name: "iFood Mercado", city: "Rio de Janeiro", notes: "Delivery de mercado" },
  { name: "Cornershop / Uber", city: "Rio de Janeiro", notes: "Delivery de supermercado" },
  { name: "Feira livre da semana", city: "Rio de Janeiro", notes: "Feiras de bairro (hortifruti)" },
  { name: "CEASA RJ / atacado hortifruti", city: "Rio de Janeiro", notes: "Referência de atacado de hortifruti" },
];
